# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       hawaii-framework

# >> macros
# << macros

Summary:    Libraries for the Hawaii desktop environment
Version:    0.4.0
Release:    1
Group:      System/Libraries
License:    LGPLv2.1+
URL:        https://github.com/mauios/hawaii-framework.git
Source0:    %{name}-%{version}.tar.xz
Source100:  hawaii-framework.yaml
Requires:   qt5-qtquickcontrols
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  plasma-devel

%description
Provides libraries for the Hawaii desktop environment.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING.LIB README.md
%{_kf5_qmldir}/Hawaii/
# >> files
# << files
